### PR TITLE
Calculate PD and resistance of LDR

### PR DESCRIPTION
**Pull request by E-Paine**
A simple set of changes that we can do because we know:

1. The voltage across the entire circuit
2. The resistance of the fixed resistor (this is a constant so could be easily changed)

Please do check my logic is correct!

Note: The round for LDR PD is required so we don't see the floating-point approximations of our value and occasionally get very high precision numbers.

### CODE REVIEW

**Comment by E-Paine** [comment]
You may also wish to include a copy of the MIT licence in the repo as you are redistributing bottle

**Review by kmartinez — CHANGES_REQUESTED** [review]
nice! the R is 8200 ohms nominally.
V = 5 * ldr/(8200 + ldr)
so I make ldr = 
5 * 8200/V - 8200

**Comment by E-Paine** [comment]
> the R is 8200 ohms nominally

For the fixed resistor? I believed it was 11kΩ (brown, brown, black, red, silver - **EDIT:** I think I might have read this the wrong way round in which case I get it to be 8.2 as you said)

> V = 5 * ldr/(8200 + ldr)

Also, we are measuring the voltage across the fixed resistor rather than the LDR aren't we? (so `V = 5 * 8200 / (8200 + ldr)`; `ldr = (5 * 8200 - V * 8200) / V = 8200 * (5 - V) / V`)?

**Comment by kmartinez** [comment]
haha! it is confusing - we're measuring the voltage inbetween
but the "top" ldr is R1 and R2 is the "bottom" 8k2
so we get Vout = Vin * R2/(R1+R2)
and we solve for R1 the ldr... so I think I'm right - have a check please

**Comment by kmartinez** [comment]
Oh and the adc reading is the voltage of the mid point which you could say is the voltage across R2 (8k2) but we solve for R1

**Comment by E-Paine** [comment]
> Vout = Vin * R2/(R1+R2)

Which I believe is equivalent to `V = 5 * 8200 / (8200 + ldr)` as `Vin = 5`, `R1 = ldr` and `R2 = 8k2` (as you said)

**Comment by kmartinez** [comment]
Nice contribution Elisha!

**Pull request merged**
